import re

path = "webcms/admin/admin_api.py"
with open(path) as f:
    lines = f.readlines()

# Find the start and end of the SQLAlchemy else block
start = None
end = None
for i, line in enumerate(lines):
    if start is None and line.strip() == "else:" and i > 0 and "SQLAlchemy path" in lines[i+1]:
        start = i
    if start is not None and line.strip().startswith("return Response.json({\"updated\": False, \"error\": str(e), \"settings\": data}, 400)"):
n        end = i + 1\n        break\n\nif start is None or end is None:\n    print(f\"Could not find block: start={start}, end={end}\")\nelse:\n    print(f\"Replacing lines {start+1}-{end}\")\n    new_lines = [\n        \"            else:\\n\",\n        '                print(\"[DEBUG] Using SQLAlchemy path\")\\n',\n        \"                # Use the ORM Setting model for SQLAlchemy path\\n\",\n        \"                from webcms.models.system import Setting\\n\",\n        \"                session = self.db.get_session()\\n\",\n        \"                try:\\n\",\n        \"                    for key, value in normalized.items():\\n\",\n        \"                        type_ = self._guess_type(value)\\n\",\n        \"                        existing = session.query(Setting).filter_by(key=key).first()\\n\",\n        \"                        if existing:\\n\",\n        \"                            existing.value = str(value)\\n\",\n        \"                            existing.type = type_\\n\",\n        \"                            existing.updated_at = datetime.utcnow().isoformat()\\n\",\n        \"                        else:\\n\",\n        \"                            setting = Setting(\\n\",\n        \"                                key=key,\\n\",\n        \"                                value=str(value),\\n\",\n        \"                                type=type_,\\n\",\n        \"                                created_at=datetime.utcnow().isoformat(),\\n\",\n        \"                                updated_at=datetime.utcnow().isoformat()\\n\",\n        \"                            )\\n\",\n        \"                            session.add(setting)\\n\",\n        \"                    session.commit()\\n\",\n        \"                except Exception:\\n\",\n        \"                    session.rollback()\\n\",\n        \"                    raise\\n\",\n        \"                finally:\\n\",\n        \"                    session.close()\\n\",\n        \"\\n\",\n        '            print(\"[DEBUG] Settings updated successfully\")\\n',\n        '            return Response.json({\"updated\": True, \"settings\": normalized})\\n',\n        \"\\n\",\n        \"        except Exception as e:\\n\",\n        '            print(f\"[DEBUG] Error updating settings: {e}\")\\n',\n        \"            import traceback\\n\",\n        \"            traceback.print_exc()\\n\",\n        '            return Response.json({\"updated\": False, \"error\": str(e), \"settings\": data}, 400)\\n',\n    ]\n    lines = lines[:start] + new_lines + lines[end:]\n    with open(path, \"w\") as f:\n        f.writelines(lines)\n    print(\"fixed\")\n