import base64
from pathlib import Path
p = Path("webcms/admin/admin_api.py")
lines = p.read_text().splitlines(keepends=True)

# Find start of KosDB block (line with "if self._is_kosdb():" inside update_settings)
method_start = None
for i, line in enumerate(lines):
    if "def update_settings(self, request: Request) -> Response:" in line:
        method_start = i
        break
else: raise SystemExit("no update_settings")

start = None
for i in range(method_start, len(lines)):
    if "if self._is_kosdb():" in lines[i]:
        start = i
        break
else: raise SystemExit("no kosdb block")

end = None
for i in range(start+1, len(lines)):
    if lines[i].strip() == "else:":
        end = i
        break
else: raise SystemExit("no else block")

new_block = base64.b64decode("ICAgICAgICAgICAgaWYgc2VsZi5faXNfa29zZGIoKToKICAgICAgICAgICAgICAgIHByaW50KCJbREVCVUddIFVzaW5nIEtvc0RCIHBhdGgiKQogICAgICAgICAgICAgICAgc2VsZi5fZW5zdXJlX3NldHRpbmdzX3RhYmxlX2tvc2RiKCkKCiAgICAgICAgICAgICAgICBlcnJvcnMgPSBbXQoKICAgICAgICAgICAgICAgICMgT1BUSU1JWkFUSU9OOiBMb2FkIGFsbCBleGlzdGluZyBrZXlzIGluIGEgc2luZ2xlIHF1ZXJ5IGluc3RlYWQKICAgICAgICAgICAgICAgICMgb2YgaXNzdWluZyBvbmUgU0VMRUNUIHBlciBzZXR0aW5nLiBUaGlzIGN1dHMgdGhlIEtvc0RCIHJvdW5kLQogICAgICAgICAgICAgICAgIyB0cmlwcyBmcm9tIDIqTiAoY2hlY2sgKyB3cml0ZSkgdG8gTisxIChvbmUgY2hlY2sgKyBOIHdyaXRlcykuCiAgICAgICAgICAgICAgICBleGlzdGluZ19rZXlzX3Jlc3VsdCA9IHNlbGYuZGIucXVlcnkoIlNFTEVDVCBzZXR0aW5nX2tleSBGUk9NIHNldHRpbmdzIikKICAgICAgICAgICAgICAgIHByaW50KGYiW0RFQlVHXSBFeGlzdGluZyBrZXlzIHF1ZXJ5IHJlc3VsdDoge2V4aXN0aW5nX2tleXNfcmVzdWx0fSIpCiAgICAgICAgICAgICAgICBpZiBleGlzdGluZ19rZXlzX3Jlc3VsdC5nZXQoJ2Vycm9yJyk6CiAgICAgICAgICAgICAgICAgICAgcHJpbnQoZiJbREVCVUddIEVycm9yIGxvYWRpbmcgZXhpc3Rpbmcga2V5czoge2V4aXN0aW5nX2tleXNfcmVzdWx0LmdldCgnZXJyb3InKX0iKQogICAgICAgICAgICAgICAgICAgIHJldHVybiBSZXNwb25zZS5qc29uKHsidXBkYXRlZCI6IEZhbHNlLCAiZXJyb3IiOiBleGlzdGluZ19rZXlzX3Jlc3VsdC5nZXQoJ2Vycm9yJyksICJzZXR0aW5ncyI6IG5vcm1hbGl6ZWR9LCA0MDApCgogICAgICAgICAgICAgICAgZXhpc3Rpbmdfa2V5cyA9IHsKICAgICAgICAgICAgICAgICAgICByb3cuZ2V0KCdzZXR0aW5nX2tleScpCiAgICAgICAgICAgICAgICAgICAgZm9yIHJvdyBpbiBleGlzdGluZ19rZXlzX3Jlc3VsdC5nZXQoJ3Jvd3MnLCBbXSkKICAgICAgICAgICAgICAgICAgICBpZiByb3cuZ2V0KCdzZXR0aW5nX2tleScpCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICBwcmludChmIltERUJVR10gRXhpc3Rpbmcga2V5czoge2V4aXN0aW5nX2tleXN9IikKCiAgICAgICAgICAgICAgICBmb3Iga2V5LCB2YWx1ZSBpbiBub3JtYWxpemVkLml0ZW1zKCk6CiAgICAgICAgICAgICAgICAgICAgdHlwZV8gPSBzZWxmLl9ndWVzc190eXBlKHZhbHVlKQogICAgICAgICAgICAgICAgICAgIHZhbF9zdHIgPSBzZWxmLl9zcWxfZXNjYXBlKHN0cih2YWx1ZSkpCgogICAgICAgICAgICAgICAgICAgIHByaW50KGYiW0RFQlVHXSBQcm9jZXNzaW5nIHNldHRpbmc6IHtrZXl9ID0ge3ZhbHVlfSAodHlwZToge3R5cGVffSkiKQoKICAgICAgICAgICAgICAgICAgICBleGlzdHMgPSBrZXkgaW4gZXhpc3Rpbmdfa2V5cwoKICAgICAgICAgICAgICAgICAgICBpZiBleGlzdHM6CiAgICAgICAgICAgICAgICAgICAgICAgIGNtZCA9ICgKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiVVBEQVRFIHNldHRpbmdzIFNFVCB2YWx1ZT0ne3ZhbF9zdHJ9JywgdHlwZT0ne3R5cGVffScgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgZiJXSEVSRSBzZXR0aW5nX2tleT0ne3NlbGYuX3NxbF9lc2NhcGUoa2V5KX0nIgogICAgICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgICAgICAgICAgY21kID0gKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgZiJJTlNFUlQgSU5UTyBzZXR0aW5ncyAoc2V0dGluZ19rZXksIHZhbHVlLCB0eXBlKSBWQUxVRVMgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgZiIoJ3tzZWxmLl9zcWxfZXNjYXBlKGtleSl9JywgJ3t2YWxfc3RyfScsICd7dHlwZV99JykiCiAgICAgICAgICAgICAgICAgICAgICAgICkKCiAgICAgICAgICAgICAgICAgICAgcHJpbnQoZiJbREVCVUddIEV4ZWN1dGluZzoge2NtZH0iKQogICAgICAgICAgICAgICAgICAgIHJlc3VsdCA9IHNlbGYuZGIuZXhlY3V0ZShjbWQpCiAgICAgICAgICAgICAgICAgICAgcHJpbnQoZiJbREVCVUddIEV4ZWN1dGUgcmVzdWx0OiB7cmVzdWx0fSIpCgogICAgICAgICAgICAgICAgICAgIGlmIHJlc3VsdCBhbmQgKCJFUlJPUiIgaW4gcmVzdWx0IG9yICJObyBkYXRhYmFzZSIgaW4gcmVzdWx0KToKICAgICAgICAgICAgICAgICAgICAgICAgZXJyb3JzLmFwcGVuZCh7ImtleSI6IGtleSwgImVycm9yIjogcmVzdWx0fSkKCiAgICAgICAgICAgICAgICBpZiBlcnJvcnM6CiAgICAgICAgICAgICAgICAgICAgcHJpbnQoZiJbREVCVUddIEVycm9ycyBkdXJpbmcgdXBkYXRlOiB7ZXJyb3JzfSIpCiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIFJlc3BvbnNlLmpzb24oeyJ1cGRhdGVkIjogRmFsc2UsICJlcnJvcnMiOiBlcnJvcnMsICJzZXR0aW5ncyI6IG5vcm1hbGl6ZWR9LCA0MDApCg==").decode()

lines = lines[:start] + [new_block] + lines[end:]
with open(str(p), "w") as f: f.writelines(lines)
print("fixed update_settings block")