import base64
from pathlib import Path
p = Path("webcms/admin/admin_api.py")
txt = p.read_text()

# Block 1: _get_model_count SQLAlchemy branch
old1 = base64.b64decode("ZWxzZToKICAgICAgICBxdWVyeSA9IHNlbGYuZGIucXVlcnkobW9kZWxfY2xhc3MpCiAgICAgICAgaWYgZmlsdGVyX2NvbmRpdGlvbnM6CiAgICAgICAgICAgIGZvciBrZXksIHZhbHVlIGluIGZpbHRlcl9jb25kaXRpb25zLml0ZW1zKCk6CiAgICAgICAgICAgICAgICBxdWVyeSA9IHF1ZXJ5LmZpbHRlcihnZXRhdHRyKG1vZGVsX2NsYXNzLCBrZXkpID09IHZhbHVlKQogICAgICAgIHJldHVybiBxdWVyeS5jb3VudCgp").decode()
new1 = base64.b64decode("ZWxzZToKICAgICAgICBzZXNzaW9uID0gc2VsZi5fc2Ffc2Vzc2lvbigpCiAgICAgICAgdHJ5OgogICAgICAgICAgICBxdWVyeSA9IHNlc3Npb24ucXVlcnkobW9kZWxfY2xhc3MpCiAgICAgICAgICAgIGlmIGZpbHRlcl9jb25kaXRpb25zOgogICAgICAgICAgICAgICAgZm9yIGtleSwgdmFsdWUgaW4gZmlsdGVyX2NvbmRpdGlvbnMuaXRlbXMoKToKICAgICAgICAgICAgICAgICAgICBxdWVyeSA9IHF1ZXJ5LmZpbHRlcihnZXRhdHRyKG1vZGVsX2NsYXNzLCBrZXkpID09IHZhbHVlKQogICAgICAgICAgICByZXR1cm4gcXVlcnkuY291bnQoKQogICAgICAgIGZpbmFsbHk6CiAgICAgICAgICAgIHNlc3Npb24uY2xvc2UoKQ==").decode()

# Block 2: _get_model_list SQLAlchemy branch
old2 = base64.b64decode("ZWxzZToKICAgICAgICBxdWVyeSA9IHNlbGYuZGIucXVlcnkobW9kZWxfY2xhc3MpCiAgICAgICAgaWYgZmlsdGVyX2NvbmRpdGlvbnM6CiAgICAgICAgICAgIGZvciBrZXksIHZhbHVlIGluIGZpbHRlcl9jb25kaXRpb25zLml0ZW1zKCk6CiAgICAgICAgICAgICAgICBxdWVyeSA9IHF1ZXJ5LmZpbHRlcihnZXRhdHRyKG1vZGVsX2NsYXNzLCBrZXkpID09IHZhbHVlKQogICAgICAgIGlmIG9yZGVyX2J5OgogICAgICAgICAgICBvcmRlcl9jb2wgPSBnZXRhdHRyKG1vZGVsX2NsYXNzLCBvcmRlcl9ieSkKICAgICAgICAgICAgaWYgZGVzYzoKICAgICAgICAgICAgICAgIG9yZGVyX2NvbCA9IG9yZGVyX2NvbC5kZXNjKCkKICAgICAgICAgICAgcXVlcnkgPSBxdWVyeS5vcmRlcl9ieShvcmRlcl9jb2wpCiAgICAgICAgaWYgbGltaXQ6CiAgICAgICAgICAgIHF1ZXJ5ID0gcXVlcnkubGltaXQobGltaXQpCiAgICAgICAgcmV0dXJuIHF1ZXJ5LmFsbCgp").decode()
new2 = base64.b64decode("ZWxzZToKICAgICAgICBzZXNzaW9uID0gc2VsZi5fc2Ffc2Vzc2lvbigpCiAgICAgICAgdHJ5OgogICAgICAgICAgICBxdWVyeSA9IHNlc3Npb24ucXVlcnkobW9kZWxfY2xhc3MpCiAgICAgICAgICAgIGlmIGZpbHRlcl9jb25kaXRpb25zOgogICAgICAgICAgICAgICAgZm9yIGtleSwgdmFsdWUgaW4gZmlsdGVyX2NvbmRpdGlvbnMuaXRlbXMoKToKICAgICAgICAgICAgICAgICAgICBxdWVyeSA9IHF1ZXJ5LmZpbHRlcihnZXRhdHRyKG1vZGVsX2NsYXNzLCBrZXkpID09IHZhbHVlKQogICAgICAgICAgICBpZiBvcmRlcl9ieToKICAgICAgICAgICAgICAgIG9yZGVyX2NvbCA9IGdldGF0dHIobW9kZWxfY2xhc3MsIG9yZGVyX2J5KQogICAgICAgICAgICAgICAgaWYgZGVzYzoKICAgICAgICAgICAgICAgICAgICBvcmRlcl9jb2wgPSBvcmRlcl9jb2wuZGVzYygpCiAgICAgICAgICAgICAgICBxdWVyeSA9IHF1ZXJ5Lm9yZGVyX2J5KG9yZGVyX2NvbCkKICAgICAgICAgICAgaWYgbGltaXQ6CiAgICAgICAgICAgICAgICBxdWVyeSA9IHF1ZXJ5LmxpbWl0KGxpbWl0KQogICAgICAgICAgICByZXR1cm4gcXVlcnkuYWxsKCkKICAgICAgICBmaW5hbGx5OgogICAgICAgICAgICBzZXNzaW9uLmNsb3NlKCk=").decode()

# Block 3: _get_model_by_id SQLAlchemy branch
old3 = base64.b64decode("ZWxzZToKICAgICAgICBxdWVyeSA9IHNlbGYuZGIucXVlcnkobW9kZWxfY2xhc3MpCiAgICAgICAgZm9yIGtleSwgdmFsdWUgaW4gZmlsdGVycy5pdGVtcygpOgogICAgICAgICAgICBxdWVyeSA9IHF1ZXJ5LmZpbHRlcihnZXRhdHRyKG1vZGVsX2NsYXNzLCBrZXkpID09IHZhbHVlKQogICAgICAgIHJldHVybiBxdWVyeS5maXJzdCgp").decode()
new3 = base64.b64decode("ZWxzZToKICAgICAgICBzZXNzaW9uID0gc2VsZi5fc2Ffc2Vzc2lvbigpCiAgICAgICAgdHJ5OgogICAgICAgICAgICBxdWVyeSA9IHNlc3Npb24ucXVlcnkobW9kZWxfY2xhc3MpCiAgICAgICAgICAgIGZvciBrZXksIHZhbHVlIGluIGZpbHRlcnMuaXRlbXMoKToKICAgICAgICAgICAgICAgIHF1ZXJ5ID0gcXVlcnkuZmlsdGVyKGdldGF0dHIobW9kZWxfY2xhc3MsIGtleSkgPT0gdmFsdWUpCiAgICAgICAgICAgIHJldHVybiBxdWVyeS5maXJzdCgpCiAgICAgICAgZmluYWxseToKICAgICAgICAgICAgc2Vzc2lvbi5jbG9zZSgp").decode()

for old, new, name in [(old1, new1, "count"), (old2, new2, "list"), (old3, new3, "by_id")]:
    if old not in txt:
        print(f"old block {name} not found")
    else:
        txt = txt.replace(old, new)
        print(f"replaced {name}")

p.write_text(txt)
print("done")